#!/bin/bash
cd /tmp/rom # Depends on where source got synced

# Normal build steps
. build/envsetup.sh
lunch fluid_umi-eng
export WITH_GAPPS=true
export SELINUX_IGNORE_NEVERALLOWS=true
export TZ=Asia/Hong_Kong
mka bootimg
